Bug 1751979 - Use backfill projects and increased parallelism for shredder
mozilla/telemetry-airflow pull request #1464
Opened 2022-02-09 22:25 UTC by relud

[Bug 1751979](https://bugzilla.mozilla.org/show_bug.cgi?id=1751979)

2022-02-09 23:45 UTC, relud commented on dags/shredder.py
> +        "moz-fx-data-backfill-10",
updated to 20 through 29

2022-02-10 00:28 UTC, whd commented on dags/shredder.py
> +        "moz-fx-data-backfill-10",
I'm not sure how billing projects interact with actual resource permissions but airflow currently doesn't have access to any backfill projects (except `moz-fx-data-shredder`), perhaps something like:

https://github.com/mozilla-services/cloudops-infra/blob/master/projects/data-bigquery-batch/tf/prod/projects/main.tf

needs to be provisioned.

2022-02-10 00:37 UTC, jasonthomas commented on dags/shredder.py
> +        "moz-fx-data-backfill-10",
`billing_project` and `quota_project` are sometimes used interchangeably, but it ties back to which project the resource will be provisioned, in this case BigQuery create on-demand jobs, is going to run in. So @whd is right, the airflow service accounts needs to be able to create jobs against the project as well.

2022-02-10 17:04 UTC, jklukas requested changes

2022-02-10 17:04 UTC, jklukas commented on dags/shredder.py
> +        "--parallelism=10",
We have `         "--parallelism=2",` a few lines above this. We should make sure to remove that line.

2022-02-10 17:55 UTC, jasonthomas commented on dags/shredder.py
> +        "moz-fx-data-backfill-10",
> Should I file a DSRE ticket about giving Airflow SAs access to run query jobs in backfill projects?

whd beat you to it https://github.com/mozilla-services/cloudops-infra/pull/3804

2022-02-10 18:48 UTC, merged