WIP: Add dag for bqetl backfill
mozilla/telemetry-airflow pull request #1598
Opened 2022-12-06 17:03 UTC by fbertsch

I didn't have a chance to test this locally. I cobbled most of this together from @mikaeld's new backfill DAG, but clearly it's much simpler.

Hopefully I can get someone from DE to test this out, but I know that actually launching a job in the pod from local airflow is a real pain so it might not happen. LMK if SRE is opposed to yoloing this and iterating in prod.

2023-02-10 13:35 UTC, fbertsch commented
@mikaeld any clue why this is failing on the param parsing? It's the same as the other backfill DAG.
```
[2022-12-06 17:06:16,196] {{dagbag.py:329}} ERROR - Failed to import: /app/dags/backfill-bqetl.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/dags/backfill-bqetl.py", line 104, in <module>
    dag = backfill_bqetl_dag()
  File "/usr/local/lib/python3.7/site-packages/airflow/models/dag.py", line 2332, in factory
    f(**f_kwargs)
  File "/app/dags/backfill-bqetl.py", line 87, in backfill_bqetl_dag
    params = __parse_string_params("{{ dag_run.conf }}")
  File "/app/dags/backfill-bqetl.py", line 37, in __parse_string_params
    params_parsed = ast.literal_eval(string_params)
  File "/usr/local/lib/python3.7/ast.py", line 91, in literal_eval
    return _convert(node_or_string)
  File "/usr/local/lib/python3.7/ast.py", line 76, in _convert
    return set(map(_convert, node.elts))
  File "/usr/local/lib/python3.7/ast.py", line 76, in _convert
    return set(map(_convert, node.elts))
  File "/usr/local/lib/python3.7/ast.py", line 90, in _convert
    return _convert_signed_num(node)
  File "/usr/local/lib/python3.7/ast.py", line 63, in _convert_signed_num
    return _convert_num(node)
  File "/usr/local/lib/python3.7/ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Attribute object at 0x7f5b0f051410>
```

2023-02-23 18:59 UTC, mikaeld requested changes

2023-02-23 18:59 UTC, mikaeld commented on dags/backfill-bqetl.py
> +        "dry_run": True,
duplicate

2023-02-23 18:59 UTC, mikaeld commented on dags/backfill-bqetl.py
> +    backfill_task = bigquery_etl_backfill(
unresolved reference

2023-02-23 18:59 UTC, mikaeld commented on dags/backfill-bqetl.py
> +        "start_date": (datetime.date.today() - datetime.timedelta(days=10)).isoformat(),
use the new `Param` class (see current backfill.py implementation

2023-02-23 21:57 UTC, fbertsch commented on dags/backfill-bqetl.py
> +        "dry_run": True,
```suggestion
```

2023-03-01 22:05 UTC, mikaeld commented on dags/backfill-bqetl.py
> +            raise ValueError(f"`start_date`={self.start_date} is greater than `end_date`={self.end_date}")
This should be in dags/utils/backfill.py

2023-03-01 22:06 UTC, mikaeld commented on dags/backfill-bqetl.py
> +    return True
This is no longer required; we are using Airflow 2.3 which supports the `Param` model, see current backfill DAG implementation.

2023-03-01 22:11 UTC, mikaeld requested changes

2023-03-01 22:11 UTC, mikaeld commented on dags/utils/gcp.py
> +        excludes: typing.List[str] = None,
types should be `Optional[str]` or use the new annotation syntax

```python
from __future__ import annotations
...
    end_date: str | None = None,
```

2023-03-01 22:11 UTC, mikaeld commented on dags/utils/gcp.py
> +        project_id = "moz-fx-data-shared-prod"
this should be a default kwarg value instead of being tested here

2023-03-01 22:11 UTC, mikaeld commented on dags/utils/gcp.py
> +        args += ["--no-partition"]
`append` or `extend` methods are preferable

2023-03-01 22:11 UTC, mikaeld commented on dags/utils/gcp.py
> +    if dryrun:
unresolved reference `dryrun`, should be dry_run to match function signature.

2023-03-03 19:36 UTC, mikaeld commented
I've extracted the JSON pod definition from the error output. Error message states cannot unmarshal number into Go struct field Container.spec.containers.args of type string 

```json
{
  "apiVersion": "v1",
  "kind": "Pod",
  "metadata": {
    "annotations": {
      "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    },
    "labels": {
      "dag_id": "backfill_bqetl",
      "task_id": "bigquery_etl_backfill",
      "run_id": "manual__2023-03-03T1915300000-23490cb28",
      "kubernetes_pod_operator": "True",
      "try_number": "1",
      "airflow_version": "2.3.3"
    },
    "name": "bigquery-etl-backfill-877d1ceecfa44462841182d1e6c9f173",
    "namespace": "default"
  },
  "spec": {
    "affinity": {},
    "containers": [
      {
        "args": [
          "script/bqetl",
          "query",
          "backfill",
          "google_ads_derived.campaign_conversions_by_date_v1",
          "--start-date",
          "2023-02-27",
          "--end-date",
          "2023-02-28",
          "--exclude",
          ",",
          "--parallelism",
          1
        ],
        "command": [],
        "env": [],
        "envFrom": [],
        "image": "gcr.io/moz-fx-data-airflow-prod-88e0/bigquery-etl:latest",
        "imagePullPolicy": "Always",
        "name": "base",
        "ports": [],
        "resources": {},
        "volumeMounts": []
      }
    ],
    "hostNetwork": false,
    "imagePullSecrets": [],
    "initContainers": [],
    "nodeSelector": {},
    "restartPolicy": "Never",
    "securityContext": {},
    "tolerations": [],
    "volumes": []
  }
}
```

the trailing `1` in `args` is definitely one of the issue. `args` is a string array but `1` of type `number`. Also, is the `","` arg necessary?

### Recommended fix
1. remove command generation code from bigquery_etl_backfill() , add it as a BackfillParams class method such as
```python
@dataclasses.dataclass
class BackfillParams:
    destination_table: str
    dataset_id: str
    start_date: str
    end_date: str
    project_id: str
    excludes: List[str]
    dry_run: bool
    parallelism: int
    no_partition: bool

    def validate_date_range(self) -> None:
        start_date = datetime.datetime.fromisoformat(self.start_date)
        end_date = datetime.datetime.fromisoformat(self.end_date)
        if start_date > end_date:
            raise ValueError(
                f"`start_date`={self.start_date} is greater than `end_date`={self.end_date}")

    def generate_backfill_command(self) -> list[str]:
        ...
```
2. Verify `generate_backfill_command` side effect using unit tests. Your command generation code is now decoupled, add unit tests. See `tests/utils/test_backfill.py` for example.
3. Use dependency injection. Use a `BackfillParams` instance as kwarg in `bigquery_etl_backfill`

2023-03-21 20:43 UTC, mikaeld commented
@fbertsch any update

2023-03-24 19:57 UTC, fbertsch commented
@mikaeld @ANich is going to pick this up

2023-06-21 17:59 UTC, closed without merging